"""Tests for CUDA codegen — IR → CUDA C source."""

import locomp
from locomp.frontend import compile_kernel
from locomp.optimizer import optimize
from locomp.backends.cuda_codegen import compile_to_cuda


def _codegen(fn, constexpr_values=None):
    ir = compile_kernel(fn)
    ir = optimize(ir, target="cuda")
    src, param_map = compile_to_cuda(ir, constexpr_values=constexpr_values or {})
    return src, param_map


# ─────────────────────────────────────────────────────────────────────────────
# Basic structure tests
# ─────────────────────────────────────────────────────────────────────────────

def test_cuda_has_headers():
    def vec_add(A: locomp.Tensor, B: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        a = locomp.load(A + i)
        b = locomp.load(B + i)
        locomp.store(Out + i, a + b)

    src, _ = _codegen(vec_add, {"N": 1024})
    assert "#include <stdint.h>" in src
    assert "#include <cuda_fp16.h>" in src
    assert "Generated by locomp" in src


def test_cuda_kernel_has_global():
    def vec_add(A: locomp.Tensor, B: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        a = locomp.load(A + i)
        b = locomp.load(B + i)
        locomp.store(Out + i, a + b)

    src, _ = _codegen(vec_add, {"N": 1024})
    assert "__global__" in src
    assert "vec_add_kernel" in src


def test_cuda_launch_fn_extern_c():
    def vec_add(A: locomp.Tensor, B: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        a = locomp.load(A + i)
        b = locomp.load(B + i)
        locomp.store(Out + i, a + b)

    src, _ = _codegen(vec_add, {"N": 1024})
    assert 'extern "C"' in src
    assert "locomp_launch_vec_add" in src
    assert "void** _args" in src


def test_cuda_program_id_uses_blockidx():
    def k(X: locomp.Tensor, Y: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        v = locomp.load(X + i)
        locomp.store(Y + i, v)

    src, _ = _codegen(k, {"N": 64})
    assert "blockIdx.x" in src


def test_cuda_local_id_uses_threadidx():
    def k(X: locomp.Tensor, Y: locomp.Tensor, N: locomp.constexpr):
        tid = locomp.local_id(0)
        v = locomp.load(X + tid)
        locomp.store(Y + tid, v)

    src, _ = _codegen(k, {"N": 64})
    assert "threadIdx.x" in src


def test_cuda_barrier_uses_syncthreads():
    def k(X: locomp.Tensor, Y: locomp.Tensor, N: locomp.constexpr):
        smem = locomp.shared_memory(64)
        tid = locomp.local_id(0)
        v = locomp.load(X + tid)
        locomp.shared_store(smem, tid, v)
        locomp.barrier()
        out = locomp.shared_load(smem, tid)
        locomp.store(Y + tid, out)

    src, _ = _codegen(k, {"N": 64})
    assert "__syncthreads()" in src


def test_cuda_tiled_load_uses_loop():
    def k(A: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        offs = locomp.arange(0, 64)
        a = locomp.load(A + i * 64 + offs)
        locomp.store(Out + i * 64 + offs, a)

    src, _ = _codegen(k, {"N": 64})
    # CUDA tiled load emits a loop (not RVV intrinsics)
    assert "for" in src
    assert "[_i]" in src


def test_cuda_simd_sum_uses_shfl():
    def k(X: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        v = locomp.load(X + i)
        s = locomp.simd_sum(v)
        locomp.store(Out + i, s)

    src, _ = _codegen(k, {"N": 64})
    assert "__shfl_down_sync" in src


def test_cuda_atomic_add():
    def k(X: locomp.Tensor, Out: locomp.Tensor):
        i = locomp.program_id(0)
        v = locomp.load(X + i)
        locomp.atomic_add(Out, v)

    src, _ = _codegen(k)
    assert "atomicAdd" in src


def test_cuda_constexpr_inlined():
    def k(X: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        acc = 0.0
        for j in range(N):
            v = locomp.load(X + i * N + j)
            acc = acc + v
        locomp.store(Out + i, acc)

    src, param_map = _codegen(k, {"N": 512})
    # N should not appear as a kernel parameter
    assert "N" not in param_map
    # N inlined as 512 in the loop bound
    assert "512" in src


def test_cuda_for_loop_codegen():
    def k(X: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        acc = 0.0
        for j in range(N):
            v = locomp.load(X + i * N + j)
            acc = acc + v
        locomp.store(Out + i, acc)

    src, _ = _codegen(k, {"N": 16})
    assert "for (" in src


def test_cuda_if_else_codegen():
    def k(X: locomp.Tensor, Out: locomp.Tensor, N: locomp.constexpr):
        i = locomp.program_id(0)
        v = locomp.load(X + i)
        if v > 0.0:
            locomp.store(Out + i, v)
        else:
            locomp.store(Out + i, 0.0)

    src, _ = _codegen(k, {"N": 64})
    assert "if (" in src
    assert "} else {" in src


def test_cuda_param_map_excludes_constexpr():
    def k(A: locomp.Tensor, B: locomp.Tensor, Out: locomp.Tensor,
          N: locomp.constexpr, D: locomp.constexpr):
        i = locomp.program_id(0)
        a = locomp.load(A + i)
        locomp.store(Out + i, a)

    _, param_map = _codegen(k, {"N": 32, "D": 16})
    assert "N" not in param_map
    assert "D" not in param_map
    assert "A" in param_map
    assert "B" in param_map
    assert "Out" in param_map
